### ISSUE TITLE
How should we refer to an application?

### ISSUE THREAD

**Issue by peteryates** [DFE-Digital/npq-registration#1089]
Currently when someone registers for an NPQ their data is stored in as an `Application`. These applications are sent to ECF where they're dealt with from a lead provider/payment point of view.

Now we're separating NPQ so it's standalone the application will be joined to declarations, and declarations tell us about the _training_ a person is receiving, not their application for that training.

The model still works for this and the relationship is clean, but the name 'applications' might not be accurate and could possibly mislead people unfamiliar with the domain.

## Other suggestions to be discussed

* **Registration**
* **Training**

**Comment by kerry-b** [comment]
Previous research session with NPQ Reg bought up 'application' as a term.
Users tend to refer to signing up with an LP as the 'application' and signing up with DfE as a 'registration'.
They flagged that the inconsistency can cause confusion when talking to users.

Planning a follow up session so will poke on this further.

**Comment by peteryates** [comment]
Another point here is that we refer to it as an 'application' throughout the API and API docs, so providers will be familiar with it. Maybe this is one to leave for API v4.
